inherits = "base16_charm"

"constant"  = "violet"

"ui.virtual.ruler" = { bg = "dark-gray", fg = "black" }

[palette]
"violet"        = "#d28fff" # oklch(76% 0.17 310)
"magenta"       = "#fe7ccb" # oklch(76% 0.18 345)
"light-violet"  = "#d3a1ff" # oklch(82% 0.12 310)
"light-magenta" = "#ff9ed9" # oklch(82% 0.14 345)
"dark-gray"     = "#292b30" # oklch(29% 0.01 266)
